### ISSUE TITLE
minor bug in setup.py

### ISSUE THREAD

**Issue by NejcHirci** [tgherzog/wbgapi#21]
Because you are importing __version__ from wbgapi, the installation process requires for packages [requests, tabulate, PyYAML] to be installed, when installing from source, which seems an unnecessary complication.

Bug:
```
~\\wbgapi-1.0.7\\setup.py'"'"';
 __file__='"'"'~\\\wbgapi-1.0.7\\setup.py'"'"';
f = getattr(tokenize, '"'"'open'"'"', open)(__file__) 
if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');
code = f.read().replace('"'"'\r\n'"'"','"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec
'"'"'))' 
egg_info --egg-base '~\AppData\Local\Temp\pip-pip-egg-info-s0r8yz9w' cwd: ~\wbgapi-1.0.7\
    
Complete output (7 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "~\wbgapi-1.0.7\setup.py", line 5, in <module>
    from wbgapi.__version__ import __version__ as pkgVersion
    File "~\wbgapi-1.0.7\wbgapi\__init__.py", line 9, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
```

**Comment by tgherzog** [comment]
The import code in setup.py is now removed in version 1.0.14
